hostname *

# Copy neovim config (resolve symlink to get actual files)
copy --dest=.config/nvim --exclude=.git --symlink-strategy=resolve .config/nvim

# Removed tmux config copy because all devices now use nix and it might be a potential cause of conflicts due to staleness.

# Use the remote's default login shell (don't force zsh if not installed)
# login_shell zsh
env ZDOTDIR=$HOME/.local/share/kitty-ssh/zsh
copy --dest=.local/share/kitty-ssh/zsh/.zshrc --symlink-strategy=resolve .config/kitty/remote-zsh/.zshrc
copy --dest=.local/share/kitty-ssh/remote-shell.sh --symlink-strategy=resolve .config/kitty/remote-shell.sh
login_shell .local/share/kitty-ssh/remote-shell.sh
