{ config, lib, pkgs, ... }:

let
  cfg = config.services.tpotInference;
  needsWriter = cfg.llamaImage != null;
  imageArg = lib.escapeShellArg (toString cfg.llamaImage);
  modelRoot = "/models/serving/writer-qwen3-4b-sft-v3";
  apiWrapper = pkgs.writeShellApplication {
    name = "tpot-inference-api-wrapper";
    runtimeInputs = [ pkgs.coreutils pkgs.tailscale pkgs.uv ];
    text = ''
      TSIP=""
      for _ in $(seq 1 30); do
        TSIP="$(tailscale ip -4 2>/dev/null | head -n1 || true)"
        if [ -n "$TSIP" ]; then break; fi
        sleep 1
      done
      if [ -z "$TSIP" ]; then
        echo "tpot-inference: could not resolve tailscale IPv4 within 30s" >&2
        exit 1
      fi
      exec uv run --frozen --extra service uvicorn tpot_taste.service:app --host "$TSIP" --port ${toString cfg.apiPort}
    '';
  };
  scorerWrapper = pkgs.writeShellApplication {
    name = "tpot-scorer-wrapper";
    runtimeInputs = [ pkgs.coreutils pkgs.uv ];
    text = ''
      exec uv run --frozen --extra service --extra train uvicorn tpot_taste.scorer_worker:app --host 127.0.0.1 --port ${toString cfg.scorerPort}
    '';
  };
  writerWrapper = pkgs.writeShellApplication {
    name = "tpot-writer-llama-wrapper";
    runtimeInputs = [ pkgs.coreutils pkgs.docker ];
    text = ''
      if [ ! -f ${lib.escapeShellArg cfg.registryPath} ]; then
        echo "tpot-writer-llama: missing registry ${cfg.registryPath}" >&2
        exit 1
      fi
      for _ in $(seq 1 30); do
        if docker info >/dev/null 2>&1; then break; fi
        sleep 1
      done
      if ! docker info >/dev/null 2>&1; then
        echo "tpot-writer-llama: docker is not ready" >&2
        exit 1
      fi
      # CDI device syntax: --gpus all fails under this docker's CDI-only setup.
      # GGML_CUDA_ENABLE_UNIFIED_MEMORY must NOT be set at all — llama.cpp
      # checks for the variable's presence, not its value, and unified memory
      # on WSL2 pages through /dev/dxg at <1 tok/s.
      exec docker run --rm \
        --network host \
        --device nvidia.com/gpu=all \
        --entrypoint ${lib.escapeShellArg cfg.llamaCommand} \
        -v ${lib.escapeShellArg "${cfg.repoPath}/models/serving:/models/serving:ro"} \
        ${imageArg} \
        -m ${modelRoot}/Qwen3-4B-Instruct-2507-Q4_K_M.gguf \
        --lora ${modelRoot}/tpot-writer-qwen3-4b-sft-v3-lora.gguf \
        --host 127.0.0.1 \
        --port ${toString cfg.writerPort} \
        --device CUDA0 \
        --n-gpu-layers all \
        --split-mode none \
        --ctx-size 4096 \
        --parallel 1 \
        --fit off \
        --metrics \
        --no-webui
    '';
  };
in
{
  options.services.tpotInference = {
    enable = lib.mkEnableOption "tailnet-only TPOT inference API";

    repoPath = lib.mkOption {
      type = lib.types.str;
      default = "/home/elijah/tpot-taste-auto-research";
      description = "Checkout containing the TPOT service code and local serving artifacts.";
    };

    envFile = lib.mkOption {
      type = lib.types.str;
      default = "%h/.config/tpot-inference/env";
      description = "Systemd EnvironmentFile containing TPOT_INFERENCE_TOKEN and optional thresholds.";
    };

    registryPath = lib.mkOption {
      type = lib.types.str;
      default = "/home/elijah/tpot-taste-auto-research/models/serving/registry.json";
      description = "Local model serving registry generated by scripts/export_writer_gguf.py.";
    };

    llamaImage = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "ghcr.io/ggml-org/llama.cpp:server-cuda@sha256:...";
      description = "Pinned llama.cpp CUDA image digest used by the writer worker.";
    };

    llamaCommand = lib.mkOption {
      type = lib.types.str;
      default = "/app/llama-server";
      description = "Entrypoint binary inside the llama.cpp image (passed via --entrypoint).";
    };

    apiPort = lib.mkOption { type = lib.types.port; default = 18180; };
    writerPort = lib.mkOption { type = lib.types.port; default = 18181; };
    scorerPort = lib.mkOption { type = lib.types.port; default = 18182; };
  };

  config = lib.mkIf cfg.enable {
    assertions = [{
      assertion = needsWriter;
      message = "services.tpotInference.llamaImage must be set to a pinned llama.cpp image digest before enabling.";
    }];

    systemd.user.services.tpot-inference-api = {
      Unit = {
        Description = "TPOT tailnet inference API";
        Wants = [ "network-online.target" ];
        After = [ "network-online.target" ];
        ConditionPathExists = "${cfg.repoPath}/pyproject.toml";
      };
      Service = {
        Type = "simple";
        ExecStart = "${apiWrapper}/bin/tpot-inference-api-wrapper";
        WorkingDirectory = cfg.repoPath;
        EnvironmentFile = cfg.envFile;
        Environment = [
          "PYTHONUNBUFFERED=1"
          # The API holds no CUDA state, but it does run the HF tokenizer for
          # token-ID parity with the writer, and transformers imports numpy —
          # whose wheel needs these shared libs on NixOS.
          "LD_LIBRARY_PATH=/usr/lib/wsl/lib:${lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib pkgs.zlib ]}"
          "TPOT_REGISTRY_PATH=${cfg.registryPath}"
          "TPOT_WRITER_URL=http://127.0.0.1:${toString cfg.writerPort}"
          "TPOT_SCORER_URL=http://127.0.0.1:${toString cfg.scorerPort}"
        ];
        Restart = "on-failure";
        RestartSec = 5;
      };
      Install.WantedBy = [ "default.target" ];
    };

    systemd.user.services.tpot-scorer = {
      Unit = {
        Description = "TPOT Python scorer worker";
        ConditionPathExists = "${cfg.repoPath}/pyproject.toml";
      };
      Service = {
        Type = "simple";
        ExecStart = "${scorerWrapper}/bin/tpot-scorer-wrapper";
        WorkingDirectory = cfg.repoPath;
        Environment = [
          "PYTHONUNBUFFERED=1"
          "TPOT_SCORER_REQUIRE_CUDA=1"
          "TPOT_SCORER_ADAPTER=${cfg.repoPath}/outputs/scorer/qwen3b-bt-taste-LOCKED"
          # Mirrors the repo devShell: WSL2 libcuda passthrough + shared libs
          # binary wheels (numpy, torch) link against but can't find on NixOS.
          "LD_LIBRARY_PATH=/usr/lib/wsl/lib:${lib.makeLibraryPath [ pkgs.stdenv.cc.cc.lib pkgs.zlib ]}"
          "TRITON_LIBCUDA_PATH=/usr/lib/wsl/lib"
        ];
        # uv run doesn't exec its child, so the API's `systemctl stop` lands
        # as SIGTERM on uv (exit 143) while uvicorn shuts down cleanly.
        SuccessExitStatus = "143";
        Restart = "no";
      };
    };

    systemd.user.services.tpot-writer-llama = {
      Unit = {
        Description = "TPOT llama.cpp writer worker";
        ConditionPathExists = cfg.registryPath;
        StartLimitBurst = 2;
        StartLimitIntervalSec = 300;
      };
      Service = {
        Type = "simple";
        ExecStart = "${writerWrapper}/bin/tpot-writer-llama-wrapper";
        WorkingDirectory = cfg.repoPath;
        Restart = "no";
      };
    };
  };
}
